return {
  -- "neovim/nvim-lspconfig",
  -- opts = {
  --   inlay_hints = { enabled = false },
  --   servers = {
  --     eslint = {
  --       root_dir = function()
  --         local lazyvimRoot = require("lazyvim.util.root")
  --         return lazyvimRoot.git()
  --       end,
  --     },
  --     ts_ls = {
  --       root_dir = function()
  --         local lazyvimRoot = require("lazyvim.util.root")
  --         return lazyvimRoot.git()
  --       end,
  --     },
  --     vtsls = {
  --       root_dir = function()
  --         local lazyvimRoot = require("lazyvim.util.root")
  --         return lazyvimRoot.git()
  --       end,
  --     },
  --   },
  -- },
}
