# Terminal
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -s extended-keys on

# Mouse
set -g mouse on

# Keys
bind -n S-Enter send-keys Escape "[13;2u"

# Windows & panes
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Status bar
set -g status-position top

# +--------------------+
# | Plugins            |
# +--------------------+

set-environment -g TMUX_PLUGIN_PATH "$HOME/.dotfiles/tmux/plugins"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

run "$HOME/.dotfiles/tmux/plugins/tpm/tpm"
